const cron = require('node-cron');
const db = require('./db');
const axios = require('axios');

// Kimi K2.5 NLP Analysis via NVIDIA NIM API
async function analyzeTextWithKimi(batchText) {
    try {
        const apiKey = process.env.NVIDIA_API_KEY;
        if (!apiKey) {
            console.error("❌ [NLP Error] NVIDIA_API_KEY is missing from environment variables.");
            return null;
        }

        const url = "https://integrate.api.nvidia.com/v1/chat/completions";

        const systemPrompt = `
Você é um assistente de extração de dados estrito e militar focado em ocorrências geográficas da cidade de Ubá, Minas Gerais.
Sua missão é ler um imenso bloco de notícias rasgadas da internet e identificar interdições de vias públicas, pontos alagados, quedas de barreiras ou pontes colapsadas.

Regras de Extração e Resposta:
1. Ignore qualquer evento que não seja explicitamente dentro do município de Ubá-MG.
2. Determine a "situação" da via como EXATAMENTE UM DE: "total" (interdição total/inundado), "parcial" (meia pista), "bridge" (risco/queda de ponte).
3. VOCÊ DEVE RESPONDER UNICA E EXCLUSIVAMENTE COM UM ARRAY JSON VALIDADO. Sem formatação Markdown, sem a palavra "json" no começo, sem saudações.

Se não houver nenhum incidente relatado nas notícias providas, retorne exatamente um array vazio:
[]

Se houver 1 ou mais incidentes, retorne NESTE EXATO formato (um Array de Objetos com essas exatas 4 chaves em português):
[
  { 
    "rua": "Avenida Governador Valadares", 
    "bairro": "Centro", 
    "situação": "total", 
    "observação": "Via completamente alagada próximo à ponte principal, trânsito desviado." 
  },
  { 
    "rua": "Rodovia MG-447", 
    "bairro": "Zona Rural", 
    "situação": "parcial", 
    "observação": "Queda de barreira interditando meia pista no KM 20." 
  }
]
`;

        const payload = {
            "model": "moonshotai/kimi-k2.5",
            "messages": [
                { "role": "system", "content": systemPrompt },
                { "role": "user", "content": `[LOTE DE NOTÍCIAS PARA PROCESSAR]:\n\n${batchText}` }
            ],
            "max_tokens": 4096,
            "temperature": 0.1,
            "top_p": 1.00,
            "stream": false,
            "chat_template_kwargs": { "thinking": true }
        };

        const headers = {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "Accept": "application/json"
        };

        const response = await axios.post(url, payload, { headers, timeout: 60000 }); // Kimi thinking takes time
        const aiRawOutput = response.data.choices[0].message.content.trim();

        // Defensive JSON parsing
        let parsedArray = [];
        try {
            // Strip potential accidental markdown block formatting generated by AI
            const jsonStr = aiRawOutput.replace(/```json/g, '').replace(/```/g, '').trim();
            parsedArray = JSON.parse(jsonStr);
        } catch (parseError) {
            console.error("❌ [NLP Error] Failed to parse Kimi JSON response:", aiRawOutput);
            return null;
        }

        if (!Array.isArray(parsedArray)) {
            return null;
        }

        return parsedArray; // Array of incident objects

    } catch (error) {
        console.error("❌ [NLP Error] NVIDIA API Request Failed:", error.response?.status, error.response?.data || error.message);
        return null;
    }
}

// Puppeteer Headless: Social Media Scraper
async function scrapeSocialMedia() {
    console.log("-> [RSS/XML] Harvesting Social Media (X/Twitter via Nitter)...");
    let socialText = "";

    // Nitter exposes clean XML RSS feeds that we can download instantly via Axios 
    // without the massive RAM overhead of Chromium or Meta/X Login Blocks.
    const targets = [
        { name: "Câmara Municipal Ubá (X)", url: "https://nitter.poast.org/CamaraUba/rss" },
        { name: "PMRv (X)", url: "https://nitter.poast.org/pmrvmg/rss" }
    ];

    for (const target of targets) {
        try {
            console.log(`   * Scraping RSS: ${target.name}`);
            const response = await axios.get(target.url, { timeout: 10000 });

            // X/Twitter RSS feeds wrap the tweet text inside <title> and <description> tags
            // We just extract the raw XML and slice it to get the newest 10 tweets
            const rawXml = response.data;
            const strippedText = rawXml.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();

            socialText += `\n--- REDE SOCIAL (X): ${target.name} ---\n${strippedText.substring(0, 1500)}\n`;
        } catch (err) {
            console.log(`   ⚠️ Failed to load RSS ${target.name}: ${err.message}`);
        }
    }

    return socialText;
}

// Main Cron Job Logic - Batch Strategy
function startScraper() {
    console.log('Automated Scraping Engine Initialized (Kimi K2.5). Running every 30 mins.');

    cron.schedule('*/30 * * * *', async () => {
        console.log('[Scraping/NLP/Batch] Running the 30min routine...');

        try {
            // 1. Fetch REAL data from local portals (BATCH STRATEGY)
            console.log("-> Harvesting HTML from News Portals...");
            const portalPromises = [
                // Portais de Notícias Locais Regionais
                axios.get('https://www.guiamuriae.com.br/noticias/cidade/uba/', { timeout: 10000 }).catch(e => ({ data: "" })),
                axios.get('https://jornalonoticiario.com.br/categoria/cidade/', { timeout: 10000 }).catch(e => ({ data: "" })),
                axios.get('https://ubanews.com/', { timeout: 10000 }).catch(e => ({ data: "" })),

                // NOTA TÉCNICA SOBRE INSTAGRAM (Prefeito, Vice-Prefeito, PMRv):
                // O Instagram bloqueia acessos via "Axios" retornando a página de Login ao invés da postagem.
                // Para ler o Instagram do Vice Prefeito diretamente aqui, precisaremos de 2 caminhos no futuro:
                // 1. Usar a API Oficial do Facebook Graph (Requer aprovação burocrática da Meta).
                // 2. Usar um serviço de Web Crawling Headless (ex: Apify Instagram Scraper / Puppeteer).
                // Por hora, manteremos o foco em portais abertos jornalísticos e sites oficiais.
            ];

            const results = await Promise.all(portalPromises);

            // 2. Aggregate raw HTML (sliced to keep within model memory & avoid token bloat)
            let aggregatedHTML = "";
            results.forEach((res, index) => {
                if (res && res.data) {
                    // Extract ~8000 chars from each portal (Kimi has 128k context, so we are safe)
                    aggregatedHTML += `\n--- FONTE ${index + 1} ---\n` + res.data.substring(0, 8000);
                }
            });

            // 2.5 Run Puppeteer Headless to grab Instagram texts bypassing Meta's login wall
            const socialMediaText = await scrapeSocialMedia();
            aggregatedHTML += `\n${socialMediaText}\n`;

            if (aggregatedHTML.length < 50) {
                console.log("⚠️ Batch harvest failed or is empty, skipping cycle.");
                return;
            }

            // 3. Pass Aggregated Batch to Kimi K2.5
            console.log("-> Sending Batch to NVIDIA Kimi K2.5 for Cognitive Processing...");
            const incidentArray = await analyzeTextWithKimi(aggregatedHTML);

            if (incidentArray && incidentArray.length > 0) {
                console.log(`[NLP Validation] Kimi detected ${incidentArray.length} potential incident(s). Syncing DB...`);

                // 4. Update the Database iteratively for each valid finding
                incidentArray.forEach(nlpResult => {
                    // Check for the new Portuguese keys
                    if (!nlpResult.rua || !nlpResult.situação) return;

                    db.get('SELECT id FROM Streets WHERE name LIKE ?', [`%${nlpResult.rua}%`], (err, street) => {
                        if (err || !street) {
                            console.log(`⚠️ Kimi found incident, but street '${nlpResult.rua}' is not in Database Map.`);
                            return;
                        }

                        // Check if community already reported it (Cross-check)
                        db.get('SELECT id FROM Reports WHERE streetId = ?', [street.id], (err, report) => {
                            if (err) return;

                            const finalDesc = `[Bairro: ${nlpResult.bairro}] ${nlpResult.observação} (Extraído via Inteligência Artificial)`;

                            if (report) {
                                // Validate existing community report
                                db.run('UPDATE Reports SET isOfficial = 1, status = ?, description = ? WHERE id = ?', [nlpResult.situação, finalDesc, report.id]);
                                console.log(`✅ [Validation] Community report validation confirmed for ${nlpResult.rua}!`);
                            } else {
                                // Create brand new official auto-report
                                db.run(
                                    "INSERT INTO Reports (streetId, userId, status, description, isOfficial) VALUES (?, NULL, ?, ?, 1)",
                                    [street.id, nlpResult.situação, finalDesc]
                                );
                                console.log(`📝 [Auto-Post] Kimi system created an Official Alert for ${nlpResult.rua}.`);
                            }
                        });
                    });
                });

            } else {
                console.log('✅ [Scraping/NLP] Cicle finished. Kimi did not find any street incidents in this news batch.');
            }
        } catch (err) {
            console.error('[Scraping/NLP] Global Engine Error:', err.message);
        }
    });
}

module.exports = { startScraper, scrapeSocialMedia };
